REDHAT.ROOT = $(PWD)/../../

-include $(ROCKSROOT)/etc/Rules.mk

build:

install::
	/bin/mkdir -p -m 0755 $(ROOT)/$(PKGROOT)
	/bin/cp -r bin lib sbin $(ROOT)/$(PKGROOT)/
	mkdir -p -m 755 $(ROOT)/opt/modulefiles/applications

clean::

